user_user_index:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

user_user_show:
    path:     /{params}/mostrar
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET

user_user_new:
    path:     /criar
    defaults: { _controller: "UserBundle:User:new" }
    methods:  [GET, POST]

user_user_edit:
    path:     /{params}/editar
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  [GET, POST]

user_user_delete:
    path:     /{id}/remover
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE

user_user_csv:
    path:     /csv
    defaults: { _controller: "UserBundle:User:csv" }
    methods:  DELETE
