services:
    almoxarifado_calendar_event.access:
        class: App\Security\Almoxarifado\CalendarEventVoter
        public: false
        arguments: ['@security.access.decision_manager','@doctrine.orm.entity_manager']
        tags:
            - { name: security.voter }

    almoxarifado_equipamento.access:
        class: App\Security\Almoxarifado\EquipamentoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    almoxarifado_categoria.access:
        class: App\Security\Almoxarifado\CategoriaVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    almoxarifado_calendar_event.type:
        class: App\Form\Almoxarifado\CalendarEventType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker', '@security.token_storage']
        tags:
            - { name: form.type, alias: view }

    almoxarifado_equipamento.type:
        class: App\Form\Almoxarifado\EquipamentoType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    almoxarifado_load_data.listener:
        class: App\Listener\LoadDataListener
        arguments: ['@doctrine.orm.entity_manager','@service_container']
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }
