realizacao_index:
    path:      /
    defaults:  { _controller: CineviRealizacaoBundle:Realizacao:index }

projetos:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\ProjetoController

copiaFinals:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\CopiaFinalController
