projetos:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\ProjetoController

projetos_csv:
    path:      /csv/projetos
    defaults:  { _controller: CineviRealizacaoBundle:Projeto:getCsv }

copia_finals:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\CopiaFinalController

copia_finals_csv:
    path:      /csv/copia/finals
    defaults:  { _controller: CineviRealizacaoBundle:CopiaFinal:getCsv }

funcaos:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\FuncaoController

funcaos_csv:
    path:      /csv/funcaos
    defaults:  { _controller: CineviRealizacaoBundle:Funcao:getCsv }
