projetos:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\ProjetoController

projetos_csv:
    path:      /csv/projetos
    methods:   [GET]
    defaults:  { _controller: CineviRealizacaoBundle:Projeto:getCsv }

copias_finais:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\CopiaFinalController

copias_finais_csv:
    path:      /csv/copias-finais
    methods:   [GET]
    defaults:  { _controller: CineviRealizacaoBundle:CopiaFinal:getCsv }

funcoes:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\FuncaoController

funcoes_csv:
    path:      /csv/funcoes
    methods:   [GET]
    defaults:  { _controller: CineviRealizacaoBundle:Funcao:getCsv }

modalidades:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\ModalidadeController

modalidades_csv:
    path:      /csv/funcoes
    methods:   [GET]
    defaults:  { _controller: CineviRealizacaoBundle:Modalidade:getCsv }
