projetos:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\ProjetoController

projetos_csv:
    path:      /csv/projetos
    defaults:  { _controller: CineviRealizacaoBundle:Projeto:getCsv }

cfs:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\CfController

cfs_csv:
    path:      /csv/cfs
    defaults:  { _controller: CineviRealizacaoBundle:Cf:getCsv }

funcs:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\FuncController

funcs_csv:
    path:      /csv/funcs
    defaults:  { _controller: CineviRealizacaoBundle:Func:getCsv }
