projetos:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\ProjetoController

projetos_csv:
    path:      /csv/projetos
    defaults:  { _controller: CineviRealizacaoBundle:Projeto:getCsv }

copias_finais:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\CopiaFinalController

copias_finais_csv:
    path:      /csv/copias-finais
    defaults:  { _controller: CineviRealizacaoBundle:CopiaFinal:getCsv }

funcoes:
    type:     rest
    resource: Cinevi\RealizacaoBundle\Controller\FuncaoController

funcoes_csv:
    path:      /csv/funcoes
    defaults:  { _controller: CineviRealizacaoBundle:Funcao:getCsv }
