services:
    cinevi.access.realizacao_projeto:
        class: Cinevi\RealizacaoBundle\Authorization\Voter\ProjetoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi.realizacao.projeto_type:
        class: Cinevi\RealizacaoBundle\Form\Type\ProjetoType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker']
        tags:
            - { name: form.type, alias: view }

    cinevi.realizacao.direcao_type:
        class: Cinevi\RealizacaoBundle\Form\Type\DirecaoType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    cinevi.realizacao.producao_type:
        class: Cinevi\RealizacaoBundle\Form\Type\ProducaoType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    cinevi.realizacao.fotografia_type:
        class: Cinevi\RealizacaoBundle\Form\Type\FotografiaType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    cinevi.realizacao.som_type:
        class: Cinevi\RealizacaoBundle\Form\Type\SomType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    cinevi.realizacao.arte_type:
        class: Cinevi\RealizacaoBundle\Form\Type\ArteType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }
