services:
    cinevi_realizacao_projeto.access:
        class: Cinevi\RealizacaoBundle\Authorization\Voter\ProjetoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi_realizacao_copia_final.access:
        class: Cinevi\RealizacaoBundle\Authorization\Voter\CopiaFinalVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi_realizacao_funcoes.access:
        class: Cinevi\RealizacaoBundle\Authorization\Voter\FuncaoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi_realizacao_realizacao.form:
        class: Cinevi\RealizacaoBundle\Form\Type\RealizacaoType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker']
        tags:
            - { name: form.type, alias: view }

    cinevi_realizacao_projeto.form:
        class: Cinevi\RealizacaoBundle\Form\Type\ProjetoType
        arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@cinevi_realizacao_projeto.validation']
        tags:
            - { name: form.type, alias: view }

    cinevi_realizacao_copia_final.form:
        class: Cinevi\RealizacaoBundle\Form\Type\CopiaFinalType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@cinevi_realizacao_copia_final.validation']
        tags:
            - { name: form.type, alias: view }

    cinevi_realizacao_equipe.form:
        class: Cinevi\RealizacaoBundle\Form\Type\EquipeType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    cinevi_realizacao_projeto.validation_factory:
        class: Cinevi\RealizacaoBundle\Validation\ProjetoValidationGroupResolverFactory
        arguments: ['@security.token_storage']

    cinevi_realizacao_projeto.validation:
        class: Cinevi\RealizacaoBundle\Validation\ProjetoValidationGroupResolver
        factory: ['@cinevi_realizacao_projeto.validation_factory', create]

    cinevi_realizacao_copia_final.validation_factory:
        class: Cinevi\RealizacaoBundle\Validation\CopiaFinalValidationGroupResolverFactory
        arguments: ['@security.authorization_checker']

    cinevi_realizacao_copia_final.validation:
        class: Cinevi\RealizacaoBundle\Validation\CopiaFinalValidationGroupResolver
        factory: ['@cinevi_realizacao_copia_final.validation_factory', create]
