Cinevi\RealizacaoBundle\Entity\Realizacao:
    properties:
        user:
            - NotBlank:
                message: 'Por favor, informe a(o) responsável.'
        titulo:
            - NotBlank:
                message: 'Por favor, informe o título.'
        sinopse:
            - NotBlank:
                message: 'Por favor, informe uma sinopse.'
            - MaxLength:
                size: 255
                message: 'A sinopse não pode ter mais de 255 caracteres.'
        modalidade:
            - NotBlank:
                message: 'Por favor, informe a modalidade.'
        professor:
            - NotBlank:
                message: 'Por favor, informe o(a) professor(a) orientador.'
        genero:
            - NotBlank:
                message: 'Por favor, informe pelo menos um gênero.'
        captacao:
            - NotBlank:
                message: 'Por favor, informe o tipo de captação.'
        locacoes:
            - NotBlank:
                message: 'Por favor, informe a(s) locação(ões).'

Cinevi\RealizacaoBundle\Entity\Projeto:
    properties:
        realizacao:
            - Valid: ~
        preProducao:
            - NotBlank:
                message: 'Por favor, informe a data de pré-produção do projeto.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        dataProducao:
            - NotBlank:
                message: 'Por favor, informe a data de produção do projeto.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        posProducao:
            - NotBlank:
                message: 'Por favor, informe a data de pós-produção do projeto.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        direcao:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
        producao:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
        fotografia:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
        disciplinaFotografia:
            - NotBlank:
                message: 'Por favor, informe se já cursou a disciplina Fotografia e Iluminação.'
        som:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
        disciplinaSom:
            - NotBlank:
                message: 'Por favor, informe se já cursou a disciplina Técnica de Som em Cinema e Audiovisual.'
        arte:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
        disciplinaArte:
            - NotBlank:
                message: 'Por favor, informe se já cursou a disciplina Direção de Arte.'

Cinevi\RealizacaoBundle\Entity\CopiaFinal:
    properties:
        realizacao:
            - Valid: ~
        fichaTecnica:
            - Valid: ~

Cinevi\RealizacaoBundle\Entity\FichaTecnica:
    properties:
        equipes:
            - Valid: ~

Cinevi\RealizacaoBundle\Entity\Equipe:
    properties:
        funcao:
            - NotBlank:
                message: 'Por favor, informe a função da equipe.'
        users:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'

Cinevi\RealizacaoBundle\Entity\Funcao:
    properties:
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome da função (ex.: Direção de Fotografia).'
