services:
    config.access:
        class: App\Security\Config\ConfigVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
