fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

public:
    resource: "@CineviAdminBundle/Resources/config/public.yml"

admin:
    resource: "@CineviAdminBundle/Resources/config/routing.yml"
    prefix: /s

security:
    resource: "@CineviSecurityBundle/Resources/config/routing.yml"
    prefix: /s

almoxarifado:
    resource: "@CineviAlmoxarifadoBundle/Resources/config/routing.yml"
    prefix: /s

realizacao:
    resource: "@CineviRealizacaoBundle/Resources/config/routing.yml"
    prefix: /s

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
    prefix: /s
