fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@CineviAdminBundle/Resources/config/routing.yml"

security:
    resource: "@CineviSecurityBundle/Resources/config/routing.yml"

almoxarifado:
    resource: "@CineviAlmoxarifadoBundle/Resources/config/routing.yml"

realizacao:
    resource: "@CineviRealizacaoBundle/Resources/config/routing.yml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
