fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

security:
    resource: "@CineviSecurityBundle/Resources/config/routing.yml"
    prefix:   /

almoxarifado:
    resource: "@CineviAlmoxarifadoBundle/Resources/config/routing.yml"
    prefix:   /almoxarifado
