almoxarifado:
    resource: "Resources/config/almoxarifado/routing.yml"
    prefix: /s

config:
    resource: "Resources/config/config/routing.yml"
    prefix: /s/configuracoes

home:
    resource: "Resources/config/home/routing.yml"

index:
    resource: "Resources/config/index/routing.yml"
    prefix: /s

realizacao:
    resource: "Resources/config/realizacao/routing.yml"
    prefix: /s

user:
    resource: "Resources/config/user/routing.yml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
    prefix: /s
