user:
    resource: "@UserBundle/Resources/config/routing.yml"

index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix: /s

config:
    resource: "@ConfigBundle/Resources/config/routing.yml"
    prefix: /s

almoxarifado:
    resource: "@AlmoxarifadoBundle/Resources/config/routing.yml"
    prefix: /s

realizacao:
    resource: "@RealizacaoBundle/Resources/config/routing.yml"
    prefix: /s

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
    prefix: /s

public:
    resource: "@PublicBundle/Resources/config/public.yml"
