# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_DEPARTAMENTO: ROLE_USER
        ROLE_ALMOXARIFADO: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_DEPARTAMENTO, ROLE_ALMOXARIFADO]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: /entrar
                check_path: /verificar
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /perfil
            logout:
                path: /sair
                target: /
            logout_on_user_change: true
            anonymous:    true

    access_control:
        - { path: ^/entrar$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cadastro, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/esqueci_minha_senha, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/s/, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
