almoxarifado_categoria:
    resource: "@AlmoxarifadoBundle/Resources/config/routing/categoria.yml"
    prefix:   /categorias_reservaveis

almoxarifado_equipamento:
    resource: "@AlmoxarifadoBundle/Resources/config/routing/equipamento.yml"
    prefix:   /reservaveis

almoxarifado_reserva:
    resource: "@AlmoxarifadoBundle/Resources/config/routing/reserva.yml"
    prefix:   /reservas
