almoxarifado_categoria_index:
    path:     /
    defaults: { _controller: "AlmoxarifadoBundle:Categoria:index" }
    methods:  GET

almoxarifado_categoria_show:
    path:     /{params}/mostrar
    defaults: { _controller: "AlmoxarifadoBundle:Categoria:show" }
    methods:  GET

almoxarifado_categoria_new:
    path:     /criar
    defaults: { _controller: "AlmoxarifadoBundle:Categoria:new" }
    methods:  [GET, POST]

almoxarifado_categoria_edit:
    path:     /{params}/editar
    defaults: { _controller: "AlmoxarifadoBundle:Categoria:edit" }
    methods:  [GET, POST]

almoxarifado_categoria_delete:
    path:     /{id}/remover
    defaults: { _controller: "AlmoxarifadoBundle:Categoria:delete" }
    methods:  DELETE

almoxarifado_categoria_csv:
    path:     /csv
    defaults: { _controller: "AlmoxarifadoBundle:Categoria:csv" }
    methods:  DELETE
