services:
    security_user.access:
        class: App\Security\User\UserVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    security_user.form:
        class: App\Form\User\UserType
        arguments: ['@security.authorization_checker','@security_user.validation']
        tags:
            - { name: form.type, alias: view }

    security_profile.form:
        class: App\Form\User\ProfileType
        tags:
            - { name: form.type, alias: security_profile }

    security_registration.form:
        class: App\Form\User\RegistrationType
        tags:
            - { name: form.type, alias: security_registration }

    security_user.validation_factory:
        class: App\Validation\User\UserValidationGroupResolverFactory
        arguments: ['@security.authorization_checker']

    security_user.validation:
        class: App\Validation\User\UserValidationGroupResolver
        factory: ['@security_user.validation_factory', create]
