reservaveis:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\EquipamentoController

reservaveis_csv:
    path:      /csv/reservaveis
    defaults:  { _controller: CineviAlmoxarifadoBundle:Equipamento:getCsv }

categorias-reservaveis:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\CategoriaController

categorias-reservaveis_csv:
    path:      /csv/categorias-reservaveis
    defaults:  { _controller: CineviAlmoxarifadoBundle:Categoria:getCsv }

reservas:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\ReservaController

reservas_csv:
    path:      /csv/reservas
    defaults:  { _controller: CineviAlmoxarifadoBundle:Reserva:getCsv }
