almoxarifado_index:
    path:      /
    defaults:  { _controller: CineviAlmoxarifadoBundle:Almoxarifado:index }

equipamentos:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\EquipamentoController

categorias:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\CategoriaController

calendar_events:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\CalendarEventController
