equipamentos:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\EquipamentoController

equipamentos_csv:
    path:      /csv/equipamentos
    defaults:  { _controller: CineviAlmoxarifadoBundle:Equipamento:getCsv }

categorias:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\CategoriaController

categorias_csv:
    path:      /csv/categorias
    defaults:  { _controller: CineviAlmoxarifadoBundle:Categoria:getCsv }

reservas:
    type:     rest
    resource: Cinevi\AlmoxarifadoBundle\Controller\ReservaController

reservas_csv:
    path:      /csv/reservas
    defaults:  { _controller: CineviAlmoxarifadoBundle:Reserva:getCsv }
