services:
    cinevi.access.almoxarifado_calendarevent:
        class: Cinevi\AlmoxarifadoBundle\Authorization\Voter\CalendarEventVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi.access.almoxarifado_equipamento:
        class: Cinevi\AlmoxarifadoBundle\Authorization\Voter\EquipamentoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi.access.almoxarifado_categoria:
        class: Cinevi\AlmoxarifadoBundle\Authorization\Voter\CategoriaVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi.almoxarifado.calendarevent_type:
        class: Cinevi\AlmoxarifadoBundle\Form\Type\CalendarEventType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker']
        tags:
            - { name: form.type, alias: view }

    cinevi.almoxarifado.equipamento_type:
        class: Cinevi\AlmoxarifadoBundle\Form\Type\EquipamentoType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    # Listener
    cinevi.almoxarifado.load_data_listener:
        class: Cinevi\AlmoxarifadoBundle\Listener\LoadDataListener
        arguments: ['@doctrine.orm.entity_manager','@service_container']
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }
