Cinevi\AlmoxarifadoBundle\Entity\Categoria:
    properties:
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome da categoria.'

Cinevi\AlmoxarifadoBundle\Entity\Equipamento:
    properties:
        categoria:
            - NotBlank:
                message: 'Por favor, informe a categoria do equipamento.'
        codigo:
            - NotBlank:
                message: 'Por favor, informe o código do equipamento.'
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome do equipamento.'
        manutencao:
            - NotBlank:
                message: 'Por favor, informe se o equipamento está ou não em manutenção.'

Cinevi\AlmoxarifadoBundle\Entity\CalendarEvent:
    properties:
        user:
            - NotBlank:
                message: 'Por favor, informe o responsável pela reserva.'
        projeto:
            - NotBlank:
                message: 'Por favor, informe o projeto.'
        equipamentos:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um equipamento.'
        startDate:
            - NotBlank:
                message: 'Por favor, informe a data de início da reserva.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        endDate:
            - NotBlank:
                message: 'Por favor, informe a data de fim da reserva.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
