Cinevi\AlmoxarifadoBundle\Entity\Categoria:
    properties:
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome da categoria.'

Cinevi\AlmoxarifadoBundle\Entity\Equipamento:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: codigo
            message: 'Este código já está em uso.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: patrimonio
            message: 'Este número de patrimônio já está em uso.'
    properties:
        categoria:
            - NotBlank:
                message: 'Por favor, informe a categoria do equipamento/espaço.'
        codigo:
            - NotBlank:
                message: 'Por favor, informe o código do equipamento/espaço.'
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome do equipamento/espaço.'
        patrimonio:
            - Type:
                type: integer
                message: Por favor, informe apenas números.
        manutencao:
            - NotNull:
                message: 'Por favor, informe se o equipamento/espaço está ou não em manutenção.'
        atrasado:
            - NotNull:
                message: 'Por favor, informe se o equipamento/espaço está com a devolução atrasada ou não.'

Cinevi\AlmoxarifadoBundle\Entity\CalendarEvent:
    properties:
        user:
            - NotBlank:
                message: 'Por favor, informe o responsável pela reserva.'
        projeto:
            - NotBlank:
                message: 'Por favor, informe o projeto.'
        startDate:
            - NotBlank:
                message: 'Por favor, informe a data de início da reserva.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        endDate:
            - NotBlank:
                message: 'Por favor, informe a data de fim da reserva.'
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        equipamentos:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um equipamento/espaço.'
