almoxarifado_equipamento_index:
    path:     /
    controller: App\Controller\Almoxarifado\EquipamentoController::index
    methods:  GET

almoxarifado_equipamento_show:
    path:     /{params}/mostrar
    controller: App\Controller\Almoxarifado\EquipamentoController::show
    methods:  GET

almoxarifado_equipamento_new:
    path:     /criar
    controller: App\Controller\Almoxarifado\EquipamentoController::new
    methods:  [GET, POST]

almoxarifado_equipamento_edit:
    path:     /{params}/editar
    controller: App\Controller\Almoxarifado\EquipamentoController::edit
    methods:  [GET, POST]

almoxarifado_equipamento_delete:
    path:     /{id}/remover
    controller: App\Controller\Almoxarifado\EquipamentoController::delete
    methods:  DELETE

almoxarifado_equipamento_csv:
    path:     /csv
    controller: App\Controller\Almoxarifado\EquipamentoController::csv
    methods:  GET
