fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path:      /entrar
    methods:   [GET, POST]
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:      /verificar
    methods:   [POST]
    defaults:  { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:      /sair
    methods:   [GET, POST]
    defaults:  { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_profile_show:
    path:      /perfil
    methods:   [GET]
    defaults:  { _controller: FOSUserBundle:Profile:show }

fos_user_profile_edit:
    path:      /perfil/editar
    methods:   [GET, POST]
    defaults:  { _controller: FOSUserBundle:Profile:edit }

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_registration_register:
    path:      /cadastro
    methods:   [GET, POST]
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_registration_check_email:
    path:      /cadastro/verificar-email
    methods:   [GET]
    defaults:  { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
    path:      /cadastro/confirmar/{token}
    methods:   [GET]
    defaults:  { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
    path:      /cadastro/confirmado
    methods:   [GET]
    defaults:  { _controller: FOSUserBundle:Registration:confirmed }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_resetting_request:
    path:      /esqueci-minha-senha/requerer
    methods:   [GET]
    defaults:  { _controller: FOSUserBundle:Resetting:request }

fos_user_resetting_send_email:
    path:      /esqueci-minha-senha/enviar-email
    methods:   [POST]
    defaults:  { _controller: FOSUserBundle:Resetting:sendEmail }

fos_user_resetting_check_email:
    path:      /esqueci-minha-senha/verificar-email
    methods:   [GET]
    defaults:  { _controller: FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
    path:      /esqueci-minha-senha/redefinir/{token}
    methods:   [GET, POST]
    defaults:  { _controller: FOSUserBundle:Resetting:reset }

fos_user_change_password:
    path:      /perfil/mudar-senha
    methods:   [GET, POST]
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }

user_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /s/usuarios
