services:
    security_user.access:
        class: UserBundle\Security\UserVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    security_user.form:
        class: UserBundle\Form\UserType
        arguments: ['@security.authorization_checker','@security_user.validation']
        tags:
            - { name: form.type, alias: view }

    security_profile.form:
        class: UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: security_profile }

    security_registration.form:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: security_registration }

    security_user.validation_factory:
        class: UserBundle\Validation\UserValidationGroupResolverFactory
        arguments: ['@security.authorization_checker']

    security_user.validation:
        class: UserBundle\Validation\UserValidationGroupResolver
        factory: ['@security_user.validation_factory', create]
