services:
    realizacao_projeto.access:
        class: App\Security\Realizacao\ProjetoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_copia_final.access:
        class: App\Security\Realizacao\CopiaFinalVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_funcoes.access:
        class: App\Security\Realizacao\FuncaoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_modalidades.access:
        class: App\Security\Realizacao\ModalidadeVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_realizacao.form:
        class: App\Form\Realizacao\RealizacaoType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@security.token_storage','@realizacao_realizacao.validation']
        tags:
            - { name: form.type, alias: view }

    realizacao_projeto.form:
        class: App\Form\Realizacao\ProjetoType
        arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@realizacao_realizacao.validation']
        tags:
            - { name: form.type, alias: view }

    realizacao_copia_final.form:
        class: App\Form\Realizacao\CopiaFinalType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@realizacao_copia_final.validation']
        tags:
            - { name: form.type, alias: view }

    realizacao_equipe.form:
        class: App\Form\Realizacao\EquipeType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    realizacao_realizacao.validation_factory:
        class: App\Validation\Realizacao\RealizacaoValidationGroupResolverFactory
        arguments: ['@security.token_storage']

    realizacao_realizacao.validation:
        class: App\Validation\Realizacao\RealizacaoValidationGroupResolver
        factory: ['@realizacao_realizacao.validation_factory', create]

    realizacao_copia_final.validation_factory:
        class: App\Validation\Realizacao\CopiaFinalValidationGroupResolverFactory
        arguments: ['@security.authorization_checker']

    realizacao_copia_final.validation:
        class: App\Validation\Realizacao\CopiaFinalValidationGroupResolver
        factory: ['@realizacao_copia_final.validation_factory', create]
