usuarios:
    type:     rest
    resource: Cinevi\SecurityBundle\Controller\UserController

usuarios_csv:
    path:      /csv/usuarios
    defaults:  { _controller: CineviSecurityBundle:User:getCsv }
