services:

    cinevi_security_user.access:
        class: Cinevi\SecurityBundle\Authorization\Voter\UserVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    cinevi_security_user.form:
        class: Cinevi\SecurityBundle\Form\Type\UserType
        arguments: ['@security.authorization_checker','@cinevi_security_user.validation']
        tags:
            - { name: form.type, alias: view }

    cinevi_security_profile.form:
        class: Cinevi\SecurityBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: cinevi_security_profile }

    cinevi_security_registration.form:
        class: Cinevi\SecurityBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: cinevi_security_registration }

    cinevi_security_user.validation_factory:
        class: Cinevi\SecurityBundle\Validation\UserValidationGroupResolverFactory
        arguments: ['@security.authorization_checker']

    cinevi_security_user.validation:
        class: Cinevi\SecurityBundle\Validation\UserValidationGroupResolver
        factory: ['@cinevi_security_user.validation_factory', create]
