Cinevi\SecurityBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'Este email já está em uso.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'Este nome já está em uso.'
    properties:
        username:
            - NotBlank:
                message: 'Por favor, informe o seu nome.'
        email:
            - NotBlank:
                message: 'Por favor, informe o seu email.'
            - Email:
                message: 'Por favor, informe um endereço de email válido.'
        plainPassword:
            - NotBlank:
                message: 'Por favor, informe uma senha.'
                groups: [new]
        matricula:
            - NotBlank:
                message: 'Por favor, informe a matrícula do usuário.'
            - Type:
                type: integer
                message: Por favor, informe apenas números.
        telefone:
            - NotBlank:
                message: 'Por favor, informe o telefone do usuário.'
            - Type:
                type: integer
                message: Por favor, informe apenas números.
        confirmado:
            - NotNull:
                message: 'Por favor, informe se os dados do usuários foram confirmados ou não.'
        professor:
            - NotNull:
                message: 'Por favor, informe se o usuário é ou não um(a) professor(a).'
        roles:
            - Choice:
                choices:  [ROLE_USER, ROLE_FUNCIONARIO, ROLE_SUPER_ADMIN]
                multiple: true
                message: 'Por favor, informe um nível de permissão válido.'
                groups: [superAdmin]
