realizacao_funcao_index:
    path:     /
    defaults: { _controller: "RealizacaoBundle:Funcao:index" }
    methods:  GET

realizacao_funcao_show:
    path:     /{params}/mostrar
    defaults: { _controller: "RealizacaoBundle:Funcao:show" }
    methods:  GET

realizacao_funcao_new:
    path:     /criar
    defaults: { _controller: "RealizacaoBundle:Funcao:new" }
    methods:  [GET, POST]

realizacao_funcao_edit:
    path:     /{params}/editar
    defaults: { _controller: "RealizacaoBundle:Funcao:edit" }
    methods:  [GET, POST]

realizacao_funcao_delete:
    path:     /{id}/remover
    defaults: { _controller: "RealizacaoBundle:Funcao:delete" }
    methods:  DELETE

realizacao_funcao_csv:
    path:     /csv
    defaults: { _controller: "RealizacaoBundle:Funcao:csv" }
    methods:  DELETE
