realizacao_modalidade_index:
    path:     /
    defaults: { _controller: "RealizacaoBundle:Modalidade:index" }
    methods:  GET

realizacao_modalidade_show:
    path:     /{params}/mostrar
    defaults: { _controller: "RealizacaoBundle:Modalidade:show" }
    methods:  GET

realizacao_modalidade_new:
    path:     /criar
    defaults: { _controller: "RealizacaoBundle:Modalidade:new" }
    methods:  [GET, POST]

realizacao_modalidade_edit:
    path:     /{params}/editar
    defaults: { _controller: "RealizacaoBundle:Modalidade:edit" }
    methods:  [GET, POST]

realizacao_modalidade_delete:
    path:     /{id}/remover
    defaults: { _controller: "RealizacaoBundle:Modalidade:delete" }
    methods:  DELETE

realizacao_modalidade_csv:
    path:     /csv
    defaults: { _controller: "RealizacaoBundle:Modalidade:csv" }
    methods:  DELETE
