realizacao_projeto_index:
    path:     /
    defaults: { _controller: "RealizacaoBundle:Projeto:index" }
    methods:  GET

realizacao_projeto_show:
    path:     /{params}/mostrar
    defaults: { _controller: "RealizacaoBundle:Projeto:show" }
    methods:  GET

realizacao_projeto_new:
    path:     /criar
    defaults: { _controller: "RealizacaoBundle:Projeto:new" }
    methods:  [GET, POST]

realizacao_projeto_edit:
    path:     /{params}/editar
    defaults: { _controller: "RealizacaoBundle:Projeto:edit" }
    methods:  [GET, POST]

realizacao_projeto_delete:
    path:     /{id}/remover
    defaults: { _controller: "RealizacaoBundle:Projeto:delete" }
    methods:  DELETE

realizacao_projeto_csv:
    path:     /csv
    defaults: { _controller: "RealizacaoBundle:Projeto:csv" }
    methods:  DELETE
