realizacao_copia_final:
    resource: "@RealizacaoBundle/Resources/config/routing/copia_final.yml"
    prefix:   /copias_finais

realizacao_funcao:
    resource: "@RealizacaoBundle/Resources/config/routing/funcao.yml"
    prefix:   /funcoes

realizacao_modalidade:
    resource: "@RealizacaoBundle/Resources/config/routing/modalidade.yml"
    prefix:   /modalidades

realizacao_projeto:
    resource: "@RealizacaoBundle/Resources/config/routing/projeto.yml"
    prefix:   /projetos
