services:
    realizacao_projeto.access:
        class: RealizacaoBundle\Security\ProjetoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_copia_final.access:
        class: RealizacaoBundle\Security\CopiaFinalVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_funcoes.access:
        class: RealizacaoBundle\Security\FuncaoVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_modalidades.access:
        class: RealizacaoBundle\Security\ModalidadeVoter
        public: false
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }

    realizacao_realizacao.form:
        class: RealizacaoBundle\Form\RealizacaoType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@security.token_storage','@realizacao_realizacao.validation']
        tags:
            - { name: form.type, alias: view }

    realizacao_projeto.form:
        class: RealizacaoBundle\Form\ProjetoType
        arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@realizacao_realizacao.validation']
        tags:
            - { name: form.type, alias: view }

    realizacao_copia_final.form:
        class: RealizacaoBundle\Form\CopiaFinalType
        arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@realizacao_copia_final.validation']
        tags:
            - { name: form.type, alias: view }

    realizacao_equipe.form:
        class: RealizacaoBundle\Form\EquipeType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: view }

    realizacao_realizacao.validation_factory:
        class: RealizacaoBundle\Validation\RealizacaoValidationGroupResolverFactory
        arguments: ['@security.token_storage']

    realizacao_realizacao.validation:
        class: RealizacaoBundle\Validation\RealizacaoValidationGroupResolver
        factory: ['@realizacao_realizacao.validation_factory', create]

    realizacao_copia_final.validation_factory:
        class: RealizacaoBundle\Validation\CopiaFinalValidationGroupResolverFactory
        arguments: ['@security.authorization_checker']

    realizacao_copia_final.validation:
        class: RealizacaoBundle\Validation\CopiaFinalValidationGroupResolver
        factory: ['@realizacao_copia_final.validation_factory', create]
