RealizacaoBundle\Entity\Realizacao:
    properties:
        user:
            - NotBlank:
                message: 'Por favor, informe a(o) responsável.'
        titulo:
            - NotBlank:
                message: 'Por favor, informe o título.'
        sinopse:
            - NotBlank:
                message: 'Por favor, informe uma sinopse.'
            - Length:
                max: 255
                maxMessage: 'A sinopse não pode ter mais de 255 caracteres.'
        modalidade:
            - NotBlank:
                message: 'Por favor, informe a modalidade.'
        professor:
            - NotBlank:
                message: 'Por favor, informe o(a) professor(a) orientador.'
        genero:
            - NotBlank:
                message: 'Por favor, informe pelo menos um gênero.'
                groups: [notProfessor]
        captacao:
            - NotBlank:
                message: 'Por favor, informe o tipo de captação.'
                groups: [notProfessor]
        locacoes:
            - NotBlank:
                message: 'Por favor, informe a(s) locação(ões).'
                groups: [notProfessor]

RealizacaoBundle\Entity\Projeto:
    properties:
        realizacao:
            - Valid: ~
        preProducao:
            - NotBlank:
                message: 'Por favor, informe a data de pré-produção do projeto.'
                groups: [notProfessor]
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        dataProducao:
            - NotBlank:
                message: 'Por favor, informe a data de produção do projeto.'
                groups: [notProfessor]
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        posProducao:
            - NotBlank:
                message: 'Por favor, informe a data de pós-produção do projeto.'
                groups: [notProfessor]
            - Date:
                message: 'Por favor, informe uma data no formato DD/MM/AAAA.'
        direcao:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
                groups: [notProfessor]
        producao:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
                groups: [notProfessor]
        fotografia:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
                groups: [notProfessor]
        disciplinaFotografia:
            - NotBlank:
                message: 'Por favor, informe se já cursou(aram) a disciplina Fotografia e Iluminação.'
                groups: [notProfessor]
        som:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
                groups: [notProfessor]
        disciplinaSom:
            - NotBlank:
                message: 'Por favor, informe se já cursou(aram) a disciplina Técnica de Som em Cinema e Audiovisual.'
                groups: [notProfessor]
        arte:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'
                groups: [notProfessor]
        disciplinaArte:
            - NotBlank:
                message: 'Por favor, informe se já cursou(aram) a disciplina Design Visual.'
                groups: [notProfessor]

RealizacaoBundle\Entity\CopiaFinal:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: projeto
    properties:
        realizacao:
            - Valid: ~
        fichaTecnica:
            - Valid: ~
        linkVideo:
            - Url:
                message: Por favor, informe um link válido.
        confirmado:
            - NotNull:
                message: 'Por favor, informe se os dados do usuários foram confirmados ou não.'
                groups: [departamento]

RealizacaoBundle\Entity\FichaTecnica:
    properties:
        equipes:
            - Valid: ~

RealizacaoBundle\Entity\Equipe:
    properties:
        funcao:
            - NotBlank:
                message: 'Por favor, informe a função da equipe.'
        users:
            - Count:
                min: 1
                minMessage: 'Por favor, selecione pelo menos um usuário.'

RealizacaoBundle\Entity\Funcao:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nome
    properties:
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome da função (ex.: Direção de Fotografia).'

RealizacaoBundle\Entity\Modalidade:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nome
    properties:
        nome:
            - NotBlank:
                message: 'Por favor, informe o nome da modalidade.'
